# Порт, на котором будет работать бэкенд (внутри контейнера и локально)
server.port=8080

# Настройки подключения к SQLite
spring.datasource.url=jdbc:sqlite:./data.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Выполнять schema.sql при каждом запуске
spring.sql.init.mode=always

# Отключаем автоматическое определение диалекта (не нужно для SQLite)
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect